import '@/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { Toaster } from '@/components/ui/toaster'
import ThemeProvider from '@/components/providers/theme-provider'
import AuthProvider from '@/components/providers/session-provider'

export const metadata = {
  title: 'Next.js Admin',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
          storageKey='devpintar-theme'
        >
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
